#!/usr/bin/expect


set host     [ lindex $argv 0]
set passwd   [ lindex $argv 1]

spawn ssh $host

expect {

-re "password:" {send "$passwd\r";exp_continue}
-re " ~]#"      {send "cd /etc/ssh/\r" }
}
expect "ssh]#"     
send "echo \"PubkeyAuthentication yes \" >> sshd_config\r"
expect "ssh]#"     
send "echo \"AuthorizedKeysFile      /root/.ssh/id_rsa.pub.auto\" >> sshd_config\r"
expect "ssh]#"     
send "/etc/init.d/sshd restart\r"
expect "ssh]#"
send "exit\r"
